api:
  host: 0.0.0.0
  port: 8080
camera:
  fps: 30
  height: 720
  index: 0
  width: 1280
detection:
  confidence: 0.55
  inference_fps: 15
  iou: 0.45
  model_path: models/best.pt
game:
  counting_system: hilo
  num_decks: 1
  num_players: 1
zones:
  dealer:
    h: 0.4
    w: 1.0
    x: 0.0
    y: 0.0
  player_1:
    h: 0.6
    w: 0.5
    x: 0.0
    y: 0.4
  player_2:
    h: 0.6
    w: 0.5
    x: 0.5
    y: 0.4
